exclude_paths:
  - tmp
  - vendor

detectors:
  BooleanParameter:
    exclude:
      - "Sod::Context#respond_to_missing?"
  LongParameterList:
    enabled: false
  ModuleInitialize:
    exclude:
      - "Sod::Models"
