inherit_gem:
  caliber: config/all.yml

Metrics/AbcSize:
  AllowedMethods:
    - "process"
Metrics/ParameterLists:
  Exclude:
    - "lib/sod/models/action.rb"
    - "lib/sod/refines/option_parser.rb"
RSpec/ExampleLength:
  Exclude:
    - "spec/lib/sod/action_spec.rb"
    - "spec/lib/sod/presenters/node_spec.rb"
RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/lib/sod/types/pathname_spec.rb"
